# **PART 1: Array creation**

In [121]:
import sys
import numpy as np

In [7]:
#1.	Create a numpy array of size 10, filled with zeros

A = np.zeros((2,10))
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
#or
C = np.random.random(size=10)
D = C*0
D

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#2.	Create a numpy array with values ranging from 10 to 49 and set its datatype to float
e = np.arange(10,50, dtype= float)
e


array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

In [4]:
#3	Create a numpy matrix of 2*2 integers, filled with ones.
c = np.ones((2,2))
c

array([[1., 1.],
       [1., 1.]])

In [9]:
#4	Create a numpy matrix of 3*2 float numbers, filled with ones.
f = np.ones((3,2), dtype=float)
f

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
#5	Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones. (#hint: search the function np.ones_like( ) )
X = np.arange(6).reshape(2,3)
X

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
Y = np.ones_like(X)
Y

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
#6.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros. (hint: similar function as above exists for zeros as well)
X = np.random.random((3,3))
X

array([[0.89053585, 0.91637294, 0.65957895],
       [0.39742089, 0.52121061, 0.19961801],
       [0.69547965, 0.48811188, 0.79510849]])

In [22]:
Y = np.zeros_like(X)
Y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
#7.	Create a numpy matrix of 4*4 integers, filled with fives.
D = np.ones((4,4), dtype=int)
D*=5
D

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [44]:
# 8. Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
v = np.random.rand(3,5)
v

array([[0.41607725, 0.06988077, 0.34652011, 0.66811179, 0.87129824],
       [0.70684836, 0.99672082, 0.03427108, 0.54435932, 0.3056076 ],
       [0.38400545, 0.8503383 , 0.94630413, 0.84548977, 0.64572871]])

In [45]:
u = np.ones_like(v)
u*=7
u

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [46]:
# 9.	Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere
g = np.identity(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
#10. Create a numpy array, filled with 3 random integer values between 1 and 10.
r = np.random.randint(10, size=(1,3))
r

array([[0, 5, 7]])

In [50]:
#11. Create a 3*3*3 numpy matrix, filled with random float values.
f = np.random.rand(3,3,3)
f

array([[[0.02377276, 0.80725028, 0.06664094],
        [0.87434521, 0.87085029, 0.43907501],
        [0.19707781, 0.20770074, 0.75355917]],

       [[0.80690472, 0.23120999, 0.82241172],
        [0.60765487, 0.28138344, 0.83070269],
        [0.52238279, 0.22234514, 0.32155084]],

       [[0.1574787 , 0.9097292 , 0.50739481],
        [0.52164171, 0.26332882, 0.02243361],
        [0.67503398, 0.21032987, 0.1713283 ]]])

In [51]:
#12. Create a numpy array with numbers from 1 to 10
h = np.arange(1,11)
h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
#13	Create a numpy array with the odd numbers between 1 to 10
o = np.arange(1,11,2)
o

array([1, 3, 5, 7, 9])

In [58]:
#14.	Create a numpy array with numbers from 1 to 10, in descending order.
d = np.arange(1,11)
e = np.sort(d)[::-1]
e

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [62]:
#15.	Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
m = np.random.randint(0,9, size=(3,3))
m

array([[2, 2, 7],
       [7, 1, 6],
       [1, 4, 3]])

# **PART 2:Array indexing**

In [63]:
#1.	Given the X numpy array, show its first element

X = np.array(['A','B','C','D','E'])
X[0]

'A'

In [64]:
#2.	Given the X numpy array, show its last element

X = np.array(['A','B','C','D','E'])
X[-1]

'E'

In [65]:
#3.	Given the X numpy array, show its first three elements

X = np.array(['A','B','C','D','E'])
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [67]:
#4.	Given the X numpy array, show all middle elements

X = np.array(['A','B','C','D','E'])
X[1:4]

array(['B', 'C', 'D'], dtype='<U1')

In [68]:
#5.	Given the X numpy array, show the elements in reverse position.

X = np.array(['A','B','C','D','E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [70]:
#6.	Given the X numpy array, show the elements in an odd position.

X = np.array(['A','B','C','D','E'])
X[0::2]

array(['A', 'C', 'E'], dtype='<U1')

In [72]:
#7.	Given the X numpy matrix, show the first row’s elements.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0]

array([1, 2, 3, 4])

In [73]:
#8.	Given the X numpy matrix, show the last row elements.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[3]

array([13, 14, 15, 16])

In [74]:
#9.	Given the X numpy matrix, show the first element on first row

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
X[0][0]

1

In [75]:
#10.	Given the X numpy matrix, show the last element on last row.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[3][-1]

16

In [83]:
#11.	Given the X numpy matrix, show the first two elements on the first two rows.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
#row  column
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [95]:
#12.	Given the X numpy matrix, show the last two elements on the last two rows

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[2:, 2:]

array([[11, 12],
       [15, 16]])

# **PART 3: Array manipulation**

In [106]:
#1.	Convert the given integer numpy array to float (you need to google the function that will help you do this)

X = [-5, -3, 0, 10, 40]
X = np.array(X)
print(type(X))

Y = X.astype(float)
print(Y)

<class 'numpy.ndarray'>
[-5. -3.  0. 10. 40.]


In [109]:
#2.	Reverse the given numpy array (first element becomes last) through indexing

X = [-5, -3, 0, 10, 40]
X =np.array(X)
X[::-1]

array([40, 10,  0, -3, -5])

In [116]:
#3.	Given the X numpy array, set the fifth element equal to 1

X = np.zeros(10)
X[4] =1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [118]:
#4.	Given the X numpy matrix, change the last row with all 1

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [120]:
#5.	Given the X numpy matrix, add 5 to every element

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X +=5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [126]:
print(".▀█▀.█▄█.█▀█.█▄.█.█▄▀　█▄█.█▀█.█─█\n"
"─.█.─█▀█.█▀█.█.▀█.█▀▄　─█.─█▄█.█▄█")

.▀█▀.█▄█.█▀█.█▄.█.█▄▀　█▄█.█▀█.█─█
─.█.─█▀█.█▀█.█.▀█.█▀▄　─█.─█▄█.█▄█
